"""
    This medule solve the recover the token generated by OAuth2 API
    and sent it to get_token2 view

    json.load(fp) - fp must be a text file or
    binary file containing a json document
    -------------------------        
    json.loads(s) - s must be a str, bytes or
    bytearray instance containing a json document.
    return a python dictionary 

"""

from textwrap import dedent
from os.path import realpath, dirname
import json, os


class ManageAuthentication(object):
    
    def __init__(self):
        pass

    def solve_json_file(self, json_file):
        # os.chdir('restapi_app/managers')
        # real_path = realpath(__file__)
        # dir_name = dirname(real_path)

        mycontent = None

        try:
            myfile = open(json_file, 'r')
            mycontent = myfile.read()
            file_name = myfile.name
            myfile.close()
            print('-'*60)
            print(dedent("""
                SUCCESS
                
                File {} was opened and read successfully.
                
                """.format(file_name))
            )
            print('-'*60)
        except Exception as error:
            print('-'*60)
            print(dedent("""
                ERROR
                
                Error try to open a file.
                Python said: {}""".format(error))   
            )
            print('-'*60)

        self.show_info2user()

        new_content = json.loads(mycontent)
        
        print('\n TYPE --> {}'.format(type(new_content)))
        print('\n\n')

        print('{}'.format(new_content))
                
        os.chdir('../') 
        os.chdir('../')
       
        return new_content


    def show_info2user(self):
        info_sol = """
        ----------------------------------------
            THIS IS THE SOLUTION PERFORMED 
            USING JSON METHOD - loads() 
        ----------------------------------------
        """
        print('{}'.format(info_sol))
        print('\n\n')


